#!/bin/sh

[ -f /etc/edufw/version ] && . /etc/edufw/version
[ -f /etc/edufw/functions ] && . /etc/edufw/functions
[ -f "$HOME/.edufw/version" ] && . "$HOME/.edufw/version"
[ -f "$HOME/.edufw/functions" ] && . "$HOME/.edufw/functions"

echo "Looking for installation media ..."
INSTALL_DEV=`find_install_media`

if [ "$INSTALL_DEV" == "" ]; then
    die "Cannot find installation media"
else
    echo "Installation media found on $INSTALL_DEV"
fi

DISKS=`LANG='' parted -l 2>/dev/null | grep '^Disk /dev/' | sed 's/^Disk //' | grep -v "^$INSTALL_DEV:"`
OPTIONS=`echo "$DISKS" | awk -F: '{print $1}'`

while [ "$TARGET_DISK" == "" ]; do
    echo ''
    echo 'Which disk do you want to initialize ?'
    echo "$DISKS"
    echo -n 'Please type the device path of the disk (q to quit): '
    read resp
    if [ "$resp" == "q" ]; then
        exit 1
    fi
    if echo "$OPTIONS" | grep -q -e "^$resp$"; then
        echo ''
        echo "You choose $resp."
        TARGET_DISK="$resp"
    fi
done

echo "This will destroy all data from your disk $TARGET_DISK. Are you sure <y/N> ?"
read resp
if [ "$resp" == "y" ]; then
    echo "Erasing disque $TARGET_DISK ..."

    # Create partition table
    parted -s "$TARGET_DISK" mklabel msdos
    
    # Create a unique big partition
    SIZE=`echo "$DISKS" | grep "^$TARGET_DISK" | awk -F: '{print $2}' | awk -F. '{print $1}'`
    MB=`echo "$SIZE" | sed 's/MB$//'`
    if [ "$MB" -lt 2048 ]; then
        FIRST_SIZE=`expr "$MB" / 2`"MB"
    else
        FIRST_SIZE=1024MB
    fi
    parted -s "$TARGET_DISK" mkpart primary 10MB $FIRST_SIZE \
    	|| die "Cannot create first partition on $TARGET_DISK: $!"
    parted -s "$TARGET_DISK" mkpart primary $FIRST_SIZE $SIZE \
    	|| die "Cannot create second partition on $TARGET_DISK: $!"
    parted -s "$TARGET_DISK" set 1 boot on \
    	|| die "Cannot set partition 1 as bootable on $TARGET_DISK: $!"
    
    # Create filesystem
    mkfs.ext3 -L EDUFW "${TARGET_DISK}1" \
    	|| die "Cannot create ext3 fs on ${TARGET_DISK}1: $!"
    
    # Create filesystem
    mkfs.ext4 -L EDUFW_LOG "${TARGET_DISK}2" \
    	|| die "Cannot create ext4 fs on ${TARGET_DISK}2: $!"
    
    mount LABEL=EDUFW /mnt \
    	|| die "Cannot mount new fs on /mnt: $!"
    
    # Install boot loader
    grub-install "$TARGET_DISK" --root-directory=/mnt \
    	|| die "Cannot install grub on ${TARGET_DISK}: $!"
    
    # Copy ssh keys
    mkdir -p /mnt/config/ssh/
    cp -a /etc/ssh/ssh_host_* /mnt/config/ssh/ \
    	|| die "Cannot copy ssh keys on ${TARGET_DISK}1/config/: $!"
    
    umount /mnt \
    	|| die "Cannot umount new fs on /mnt: $!"
    
    /sbin/edufw_installimage "$INSTALL_DEV" "${EDUFW_VERSION}-${BUILDROOT_VERSION}"

fi
