#!/bin/sh

[ -f /etc/edufw/version ] && . /etc/edufw/version
[ -f /etc/edufw/functions ] && . /etc/edufw/functions
[ -f "$HOME/.edufw/version" ] && . "$HOME/.edufw/version"
[ -f "$HOME/.edufw/functions" ] && . "$HOME/.edufw/functions"

GRUB_CFG="$EDUFW_MP"'/boot/grub/grub.cfg'

cd "$EDUFW_MP" \
    || die "Cannot enter $EDUFW_MP directory: $!"

cat >"$GRUB_CFG" <<_END_
set timeout=10
set default="0"
set serial --speed=9600 --unit=0 --word=8 --parity=no --stop=1

_END_

ls -t */bzImage | while read KERNEL; do
    #echo "KERNEL: $KERNEL"
    KERNEL_PATH=$(dirname "$KERNEL")
    if [ -f "$KERNEL_PATH/initrd.bz2" ]; then
	    echo "Found version $KERNEL_PATH"
	    cat >>"$GRUB_CFG" <<_END_
menuentry "EduFW $KERNEL_PATH" {
    search --set=root --label EDUFW --hint hd0,msdos5
    linux /$KERNEL_PATH/bzImage
    initrd /$KERNEL_PATH/initrd.bz2
}

_END_
    fi
done
