#!/bin/sh

[ -f /etc/edufw/version ] && . /etc/edufw/version
[ -f /etc/edufw/functions ] && . /etc/edufw/functions
[ -f "$HOME/.edufw/version" ] && . "$HOME/.edufw/version"
[ -f "$HOME/.edufw/functions" ] && . "$HOME/.edufw/functions"

WGET="wget"

EDUFW_CA=$(get_config_file "ca.pem")
REG_SERVER_FILE=$(get_config_file ".regserver.txt")
REGID_FILE=$(get_config_file "regid.conf")
CERT_FILE=$(get_config_file "cert.pem")

REG_SERVER=$(cat "$REG_SERVER_FILE")

[ -z "$REG_SERVER" ] && die "Registration server not defined"

if [ -s "$REGID_FILE" ]; then
    . "$REGID_FILE"
    if [ -n "$regid" ]; then
        echo "Already registered as id $regid" >&2
    else
        echo "Not registered" >&2
        exit 1
    fi
fi

if [ -s "$CERT_FILE" ]; then
    echo "Certificate already downloaded" >&2
    exit 0
fi

"$WGET" --ca-certificate="$EDUFW_CA" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
RES="$?"

while [ "$RES" != 0 ]; do
    sleep 60
    "$WGET" --ca-certificate="$EDUFW_CA" -q -O"$CERT_FILE" --post-data="regid=$regid" "$REG_SERVER/get-cert/"
    RES="$?"
done

if cp "$CERT_FILE" "/edufw/config/edufw/cert.pem"; then
  :
else
  echo "ERROR: Cannot copy registration id file '$CERT_FILE' to '/edufw/config/edufw/cert.pem'" >&2
  exit 3
fi

