#!/bin/sh

[ -f /etc/edufw/version ] && . /etc/edufw/version
[ -f /etc/edufw/functions ] && . /etc/edufw/functions
[ -f "$HOME/.edufw/version" ] && . "$HOME/.edufw/version"
[ -f "$HOME/.edufw/functions" ] && . "$HOME/.edufw/functions"

mount LABEL=EDUFW "$EDUFW_MP" \
    || die "Cannot mount $EDUFW_MP: $!"

RUNNING_IMAGE=$(sed 's:.*BOOT_IMAGE=::' </proc/cmdline | sed 's:bzImage.*:bzImage:')
echo "Currently running image $RUNNING_IMAGE"

ls -t "$EDUFW_MP"/*/bzImage | sed "s:^$EDUFW_MP::" | grep -v "^$RUNNING_IMAGE$" | tail +3 | while read KERNEL; do
    KERNEL_PATH=$(dirname "$KERNEL")
    if [ -n "$KERNEL_PATH" ] && [ "$KERNEL_PATH" != "/" ]; then
        echo "Deleting $KERNEL_PATH"
        rm -rf "$EDUFW_MP/$KERNEL_PATH"
    fi
done

umount "$EDUFW_MP" \
    || die "Cannot mount $EDUFW_MP: $!"

/sbin/edufw_grubconf_gen
