#!/bin/sh

. /etc/edufw/version
. /etc/edufw/functions

echo "Copying config from hard disk ..."

if is_booting_from_iso; then
    die "Booting from iso ... doing nothing"
fi

mount LABEL=EDUFW /mnt \
    || die "Cannot mount LABEL=EDUFW on /mnt: $!"

# Copy ssh keys
cp -a /mnt/config/ssh_host_* /etc/ssh/ \
    || error "Cannot copy ssh keys from LABEL=EDUFW/config/: $!"

# Copy config
cp -a /mnt/config/edufw-config.yaml /etc/edufw/ \
    || error "Cannot copy config from LABEL=EDUFW/config/edufw-config.yaml: $!"

umount /mnt \
    || die "Cannot umount LABEL=EDUFW from /mnt: $!"

