#!/bin/sh

[ -f /etc/edufw/version ] && . /etc/edufw/version
[ -f /etc/edufw/functions ] && . /etc/edufw/functions
[ -f "$HOME/.edufw/version" ] && . "$HOME/.edufw/version"
[ -f "$HOME/.edufw/functions" ] && . "$HOME/.edufw/functions"

[ -f "$EDUFW_FIRMWARE.OK" ] && exit 0

echo "Rollbacking firmware in 30s ... \"touch $EDUFW_FIRMWARE.OK\" to cancel reboot "
sleep 30

[ -f "$EDUFW_FIRMWARE.OK" ] && exit 0

mv "$EDUFW_FIRMWARE.old" "$EDUFW_FIRMWARE" \
    && sync \
    && sleep 5 \
    && reboot
