#!/bin/sh

case "$1" in
	start|'')
		. /etc/edufw/functions
		if ! is_booting_from_iso; then
			mkdir -p /var/log
			mount LABEL=EDUFW_LOG /var/log
			mkdir -p /var/log/local
			touch /var/log/local/secure
			chmod 700 /var/log/local/secure
		fi
		;;
	stop)
		;;
esac
