#!/bin/sh

case "$1" in
	start|'')
		mkdir -p /var/log/edufw
		mount LABEL=EDUFW_LOG /var/log/edufw
		mkdir -p /var/log/edufw/local
		touch /var/log/edufw/local/secure
		chmod 700 /var/log/edufw/local/secure
		;;
	stop)
		;;
esac
