#!/bin/sh

grep -q '$1$T.j9BjLM$MUI9nx9f6.A1aU34Xu8u11' /etc/shadow \
  && NEWPASS="$(pwgen  -y -B 12 1)" \
  && echo "root passwd is $NEWPASS" \
  && echo "root passwd is $NEWPASS" >> /etc/issue \
  && passwd root <<_END_
$NEWPASS
$NEWPASS
_END_
