#!/bin/sh

find_install_media() {
    # Find installation media
    for DEV in `ls /dev/sd* /dev/sr*`; do
        if mount "$DEV" /mnt >/dev/null 2>&1; then
            if [ -e "/mnt/EDUFW_ISO-$EDUFW_VERSION" ]; then
                INSTALL_DEV="$DEV"
            fi
            umount "$DEV" >/dev/null 2>&1
            [ "$INSTALL_DEV" != "" ] && break
        fi
    done

    echo "$INSTALL_DEV"
}

is_booting_from_iso() {
    # if /proc/cmdline contains BOOT_IMAGE=/bzImage then we are booting from ISO IMAGE
    grep -q 'BOOT_IMAGE=/bzImage' /proc/cmdline
}
